# Generated by Django 2.2.4 on 2019-08-13 16:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Users', unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='device_id',
            field=models.IntegerField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='users',
            name='push_notification_id',
            field=models.IntegerField(max_length=32, unique=True),
        ),
    ]
